# Generated by Django 4.1 on 2022-08-09 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('quantidade_musicas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de musicas')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('duracao', models.FloatField(verbose_name='Duração')),
                ('genero', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gênero')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musica', to='core.artista')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('quantidade_musicas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de musicas')),
                ('duracao', models.FloatField(blank=True, default=0, null=True, verbose_name='Duração')),
                ('musica', models.ManyToManyField(to='core.musica')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
            },
        ),
    ]
